### ISSUE TITLE
Framer Library Version Update automation

### ISSUE THREAD

**Issue by kkak10** [alexchantastic/framer-bootstrap#1]
Hi :) 

This Bootstrap is very good! but that have one cons.

It is Framer Library Version automation update is very passive.

**Comment by alexchantastic** [comment]
Yes, good point. I have a plan for implementing being able to update to the latest version of Framer Library and also to peg to a specific version as well.

**Comment by alexchantastic** [comment]
@kkak10 I've updated the latest release to grab the latest build of Framer Library. You can read more about it here: https://github.com/alexchantastic/framer-bootstrap#framer-version
